### ISSUE TITLE
multithreaded state loader

### ISSUE THREAD

**Issue by levlite** [vulcanize/go-eth-state-node-iterator#1]
eth-pg-ipfs-state-snapshot currently uses the go-ethereum state node iterator. This iterator is not multithreaded and using it for loading the entire state at a late block is too slow. We should write our own version that spins out separate goroutines to concurrently iterate over sub-tries (keep spinning out new gorotuines until some depth or until some number of goroutines).

**Comment by i-norden** [comment]
Completed in #4
