### ISSUE TITLE
Rebase to v1.10.18 of root geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-eth-state-node-iterator#12]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] Release that uses the new v1.10.18 release of geth (off of https://github.com/vulcanize/go-eth-state-node-iterator/tree/release-v1.0.2)

**Comment by abdulrabbani00** [comment]
Needs Merging: https://github.com/vulcanize/go-eth-state-node-iterator/pull/13
